import { Vegetable } from "./types";

export const vegetables: Vegetable[] = [
  { id: "potato", name: "Potato", nepaliName: "Aloo", emoji: "🥔" },
  { id: "cauliflower", name: "Cauliflower", nepaliName: "Kauli", emoji: "🥦" },
  { id: "spinach", name: "Spinach", nepaliName: "Palak", emoji: "🥬" },
  { id: "mustard-greens", name: "Mustard Greens", nepaliName: "Rayo Saag", emoji: "🌿" },
  { id: "fenugreek-leaves", name: "Fenugreek Leaves", nepaliName: "Methi", emoji: "🍃" },
  { id: "bok-choy", name: "Bok Choy", nepaliName: "Bok Choy", emoji: "🥬" },
  { id: "eggplant", name: "Eggplant", nepaliName: "Bhanta", emoji: "🍆" },
  { id: "okra", name: "Okra", nepaliName: "Ramtorai", emoji: "🫛" },
  { id: "tomato", name: "Tomato", nepaliName: "Golbheda", emoji: "🍅" },
  { id: "onion", name: "Onion", nepaliName: "Pyaj", emoji: "🧅" },
  { id: "peas", name: "Peas", nepaliName: "Kerau", emoji: "🟢" },
  { id: "paneer", name: "Paneer", nepaliName: "Paneer", emoji: "🧀" },
  { id: "mushroom", name: "Mushroom", nepaliName: "Ch'au", emoji: "🍄" },
  { id: "bamboo-shoots", name: "Bamboo Shoots", nepaliName: "Tama", emoji: "🎋" },
  { id: "black-eyed-peas", name: "Black-eyed Peas", nepaliName: "Bodi", emoji: "🫘" },
  { id: "bottle-gourd", name: "Bottle Gourd", nepaliName: "Lauka", emoji: "🫒" },
  { id: "bitter-gourd", name: "Bitter Gourd", nepaliName: "Tite Karela", emoji: "🥒" },
  { id: "carrot", name: "Carrot", nepaliName: "Gajar", emoji: "🥕" },
  { id: "cabbage", name: "Cabbage", nepaliName: "Bandakobi", emoji: "🥗" },
  { id: "bell-pepper", name: "Bell Pepper", nepaliName: "Bhede Khursani", emoji: "🫑" },
  { id: "beetroot", name: "Beetroot", nepaliName: "Chukandar", emoji: "🟣" },
  { id: "lentils", name: "Lentils", nepaliName: "Dal", emoji: "🫘" },
  { id: "chickpeas", name: "Chickpeas", nepaliName: "Chana", emoji: "🟤" },
  { id: "beans", name: "Green Beans", nepaliName: "Simi", emoji: "🫘" },
  { id: "radish", name: "Radish", nepaliName: "Mula", emoji: "⚪" },
];
